services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bingo_dev
      POSTGRES_USER: bingo_app
      POSTGRES_PASSWORD: bingo_pw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
