/**
 * Hardcoded list of Minecraft bingo goals.
 * Must contain at least 25 entries; 50+ gives variety across different seeds.
 */
export const GOALS: readonly string[] = [
  // Crafting & tools
  'Craft a fishing rod',
  'Craft a compass',
  'Craft a clock',
  'Craft an anvil',
  'Craft a bookshelf',
  'Craft a jukebox',
  'Craft a lead',
  'Craft a name tag',
  'Craft waxed weathered cut copper stairs',
  'Craft a copper spear',
  'Craft chisled tuff bricks',
  'Craft a block from any ore',
  'Craft an eye of ender',

  // Mining & resources
  'Mine a diamond ore',
  'Mine an emerald ore',
  'Mine ancient debris',
  'Mine a block of obsidian',
  'Find a geode',
  'Break a monster spawner',
  'Collect a stack of iron ingots',
  'Collect a stack of gold ingots',
  'Collect a stack of coal',
  'Collect a stack of redstone dust',

  // Exploration & structures
  'Enter the Nether',
  'Find a stronghold',
  'Blow up a desert temple (and its loot!)',
  'Loot a jungle temple',
  'Loot an ocean monuments gold',
  'Loot a woodland mansion chest',
  'Loot a bastion remnant chest',
  'Enter a nether fortress',
  'Loot a shipwreck chest',
  'Find a buried treasure',
  'Find an archeological site',

  // Mobs & combat
  'Kill a creeper with fire damage',
  'Kill a skeleton with an arrow',
  'Kill an enderman with water',
  'Kill a blaze with a snowball',
  'Kill a wither skeleton with fall damage',
  'Kill a ghast with melee damage',
  'Kill a pillager',
  'Kill a drowned',
  'Kill an elder guardian',
  'Kill a hoglin',
  'Kill a phantom',
  'Make a villager die to a zombie',
  'Kill a monster at full hp in one hit',
  'Kill a nether monster with a trident',
  'Kill a mob with magic damage',

  // Food & farming
  'Eat a golden apple',
  'Eat a suspicious stew',
  'Brew a potion of Strength',
  'Brew a potion of Night Vision',
  'Brew a splash potion',
  'Grow a pumpkin',
  'Grow a melon',
  'Breed two cows',
  'Breed two pigs',
  'Tame a wolf',
  'Tame a cat',
  'Tame a horse',
  'Make a purple sheep',

  // Achievements & feats
  'Wear a full set of iron armor',
  'Wear a full set of diamond armor',
  'Enchant an item using a table',
  'Trade with a villager',
  'Travel 1000 blocks from spawn',
  'Sleep in a bed in the Nether (attempt)',
  'Reach the top of the world (Y=320)',
  'Ride a pig with a carrot on a stick',
  'Ride a strider in the Nether',
  'Fill a map completely',
  'Place a banner on a shield',
  'Get to level 30',

  // Completely random!
  'Put armor on a tamed wolf',
  'Look at the sun with a spyglass',
  'Get struck by lightning',
  'Throw an enchanted tool in lava',
  'Equip a full armor set with trimmings',
  'Equip an enchanted golden helmet with trim',
  'Lay down in a cauldron of lava',
  'Have all 3 types of nugget in your inventory',
  'Fish a fishing rod',
  'Type a message in chat and be ignored',
  'Die 5 times in a row without your opponent dying',
  'Shoot a projectile from a dispenser',
  'Launch an explosive firework',
  'Throw an ender pearl without having it land',
  'Jump into a pool of lava in the nether',
  'Make a redstone circuit with at least 3 different components',

];
